# -*- coding: utf-8 -*-
"""Numpy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fi95PMNl8AwYYs-f2pS6X3GrBAuA-FS-
"""

#Import library
import numpy as np
import sys

#Data
a = np.array([1,2,3], dtype='int32')
print(a)

b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

#Get Dimension
a.ndim

#Explaination
#Dimension (chiều) đề cập đến số lượng trục (axes) mà một mảng NumPy (ndarray) có.
#Bạn có thể hiểu mỗi chiều như một cách để bạn có thể di chuyển qua các phần tử của mảng.

#Get shape
b.shape

#Get type
a.dtype

#Get size
a.itemsize
#b.itemsize #Float will 8

#Get total size
a.nbytes #a.size * a.itemsize

a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

#Get a specific element [r, c]
a[1, 5]
#Explaination
#-----------------------------------------------------------------------
#       | Cột 0 | Cột 1 | Cột 2 | Cột 3 | Cột 4 | Cột 5 | Cột 6 |
#----------------------------------------------------------------------
# Hàng 0|   1   |   2   |   3   |   4   |   5   |   6   |   7   |
#-----------------------------------------------------------------------
# Hàng 1|   8   |   9   |   10   |   11   |   12   |   13   |   14   |
#a[1, 5] means row 0 and column 5 which is 13

#Get a specific row
a[0, :]

#Get a specific column
a[:, 2]

#Getting a little fancy [startindex:endindex:stepsize]
a[0, 1:-2:2]

a[1,5] = 20
print(a)

a[1,2] = 5
print(a)



b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
 print(b)

b[0,1,1]
#The result is 4 because choose the first block, first row and first column

b[:,0,0]
#: means both

#replace
b[:,1,:] = [[9,9],[8,8]]