# -*- coding: utf-8 -*-
"""Numpy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fi95PMNl8AwYYs-f2pS6X3GrBAuA-FS-
"""

#Reorginizing Arrays

import numpy as np
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,3))
print(after)

#Vertically staking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2,v2])

#Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))


np.hstack((h1,h2))