# -*- coding: utf-8 -*-
"""Numpy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fi95PMNl8AwYYs-f2pS6X3GrBAuA-FS-
"""

#This is for Mathematics

#Import library
import numpy as np

a = np.array([1,2,3,4])
print(a)
#Division
b = a/2
print(b)
#Subtraction
c = a-2
print(c)
#Multiplication
d = a*2
print(d)
#Sqrt
e = a**2
print(e)
f = np.sin(a)
g = np.cos(a)
print(f)
print(g)

x = np.array([1,0,1,0])
a/x

#Linear Algebra
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

c = np.identity(3)
np.linalg.det(c)

